version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: pg_ny_taxi
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
    external: true